- hosts: all
  gather_facts: no
  vars:
    repo: git://github.com/apache/hadoop-common
    branch: trunk
    maven_opts: -Xmx2048m
    extra_params: 
    module: .
    build_dir: build
  tasks:
  - name: fetch sources
    git: repo=$repo dest=$target_dir version=$branch
  - name: build sources
    shell: PATH=\$PATH:$extra_path MAVEN_OPTS=$maven_opts mvn clean install -DskipTests >${inventory_hostname}.out 2>&1 chdir=$target_dir
  - name: set tests to run
    copy: dest=$target_dir src=$build_dir/tests_${inventory_hostname}
  - name: run tests
    shell: PATH=\$PATH:$extra_path MAVEN_OPTS=$maven_opts mvn -f $module/pom.xml -Dtest=`cat tests_${inventory_hostname}` -Dmaven.test.failure.ignore=true test $extra_params >>${inventory_hostname}.out 2>&1 chdir=$target_dir
  - name: archive reports
    shell: tar -czf reports.tar.gz ${inventory_hostname}.out `find . -type d -name surefire-reports` chdir=$target_dir
  - name: fetch reports
    fetch: src=$target_dir/reports.tar.gz dest=$build_dir
