- hosts: all
  gather_facts: no
  vars:
    repo: git://github.com/griddynamics/yhadoop-common
    branch: fb-YAHOO-238-trunk-gd
    maven_opts: -Xmx2048m
    module: hadoop-common-project/hadoop-common
    build_dir: build
  tasks:
  - name: fetch sources
    git: repo=$repo dest=$target_dir version=$branch
  - name: build sources
    shell: PATH=\$PATH:$extra_path MAVEN_OPTS=$maven_opts mvn clean install -DskipTests chdir=$target_dir
  - name: set tests to run
    copy: dest=$target_dir src=tests_${inventory_hostname}
  - name: run tests
    shell: PATH=\$PATH:$extra_path MAVEN_OPTS=$maven_opts mvn -f $module/pom.xml -Dtest=`cat tests_${inventory_hostname}` -Dmaven.test.failure.ignore=true test -Pparallel-tests chdir=$target_dir
  - name: archive reports
    shell: tar -czf reports.tar.gz `find . -type d -name surefire-reports` chdir=$target_dir
  - name: fetch reports
    fetch: src=$target_dir/reports.tar.gz dest=$build_dir
